CREATE TABLE IF NOT EXISTS projects(
    id integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    name text NOT NULL CHECK (name <> ''),
    priority integer NOT NULL,
    description text,
    deliverydate date NOT NULL
);

CREATE TABLE IF NOT EXISTS tasks(
    id integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    name text NOT NULL CHECK (name <> ''),
    done BOOLEAN,
    projectId integer REFERENCES projects(id)
);

INSERT INTO projects(name, priority, description, deliverydate)
    VALUES ('Make a web app', 1, 'Usando js', '2019-05-12');

INSERT INTO projects(name, priority, description, deliverydate)
    VALUES ('Make a desktop app', 1, 'Usando dart', '2019-05-13');

INSERT INTO projects(name, priority, description, deliverydate)
    VALUES ('Make a app', 2, 'Usando c++', '2019-05-12');

-- INSERT TASKS DATA
INSERT INTO TASKS (name, done, projectId)
    VALUES('download Vuejs', false, 1);

INSERT INTO TASKS (name, done, projectId)
    VALUES('Create UI WEB', false, 1);

INSERT INTO TASKS (name, done, projectId)
    VALUES('download Flutter', false, 2);

INSERT INTO TASKS (name, done, projectId)
    VALUES('Desing UI', false, 2);